global:
  edition: ce

  hosts:
    domain: kube.home.ptiteigne.eu
    https: true

  ingress:
    enabled: false
    configureCertmanager: false

  certificates:
    enabled: false

  certmanager:
    enabled: false

  minio:
    enabled: false

  appConfig:
    object_store:
      enabled: false

  storageClass: rook-ceph-block

certmanager:
  install: false

certmanager-issuer:
  enabled: false

nginx-ingress:
  enabled: false

postgresql:
  install: true
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 20Gi

redis:
  install: true
  master:
    persistence:
      enabled: true
      storageClass: rook-ceph-block
      size: 10Gi

gitlab:
  webservice:
    ingress:
      enabled: false

  gitaly:
    persistence:
      enabled: true
      storageClass: rook-ceph-block
      size: 200Gi

  toolbox:
    backups:
      enabled: false

registry:
  enabled: true
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 50Gi

prometheus:
  install: false

