global:
  edition: ce

  hosts:
    domain: kube.home.ptiteigne.eu
    https: true

  ingress:
    enabled: false

  certmanager:
    enabled: false

  minio:
    enabled: false

  appConfig:
    object_store:
      enabled: true
      connection:
        secret: gitlab-object-storage
        key: connection

  storageClass: rook-ceph-block

gitlab:
  toolbox:
    backups:
      objectStorage:
        enabled: true
        config:
          secret: gitlab-object-storage
          key: connection

postgresql:
  install: true
  persistence:
    enabled: true
    size: 20Gi

redis:
  install: true
  master:
    persistence:
      enabled: true
      size: 10Gi

registry:
  enabled: true
  persistence:
    enabled: true
    size: 50Gi

nginx-ingress:
  enabled: false
